version: "3"
services:
  etl:
    build: ./data-etl
    volumes:
        - ./raw-data:/usr/src/app/data
    depends_on:
        - pgdatabase
  server:
    build: ./data-server
    ports:
        - "8000:8000"
    depends_on:
        - pgdatabase
  pgdatabase:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=admin